### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by manderson23** [legendapp/openlayers-map#1]
What is the license for this project?

**Comment by aphelionz** [comment]
idk dude, you might know better than me... what should it be? It's probably whatever Openlayers' or Polymer's is.

**Comment by manderson23** [comment]
Both polymer and openlayers are BSD license so that makes sense.

**Comment by aphelionz** [comment]
Sounds good to me. I'll add the BSD license for now. Does that help you? Do I need to do anything to my code here to make it compliant?

**Comment by aphelionz** [comment]
Ok, have a look! I added LICENSE.md

**Comment by manderson23** [comment]
Thanks.
